### PR TITLE
docs: create contributing guide

### PR DESCRIPTION
**Pull request by HassanBahati**
this pr attempts to add a contributing guide

### CODE REVIEW

**Comment by jet2018** [comment]
let me when know when it is ready for review

**Comment by HassanBahati** [comment]
@jet2018

**Comment by jet2018** [comment]
please notify people about this file by attaching a link in the readme under the contributing section. Then make another pr and we merge all of them once.

**Comment by HassanBahati** [comment]
> please notify people about this file by attaching a link in the readme under the contributing section. Then make another pr and we merge all of them once.

I have added it via [2ca7ca7](https://github.com/OSCA-Kampala-Chapter/jet-fetch/pull/4/commits/2ca7ca776185b6055a7d8e4fbbd01f2e4dde02ed)

**Pull request merged**
